### PR TITLE
feat: AC for 0029-FEES-005

### PR DESCRIPTION
**Pull request by cdummett**
Adding additional feature test "fees/immediate-amend-fees.feat" to cover AC 0029-FEES-005 in spec 0029-FEES-fees.

### CODE REVIEW

**Comment by jeremyletang** [comment]
Shouldn't this test be under `core/integration/features/verified`? cc @davidsiska-vega @Jiajia-Cui

**Comment by Jiajia-Cui** [comment]
There are 2 scenarios in the test, are they duplicated?

**Comment by cdummett** [comment]
Thanks for reviewing Jiajia, I setup the first scenario to check how fees are calculated for a placed order which resolves immediately before testing amended orders which resolve immediately. This was mostly for my own sanity, I'll remove it now as it doesn't relate to 0029-FEES-005. 

Do you have any idea why the PR is failing other checks by the way?

**Comment by Jiajia-Cui** [comment]
> 

I can run it from my end, it seems fine :)

**Review by Jiajia-Cui — APPROVED** [review]
LGTM

**Pull request merged**
