### PR TITLE
Implemented feature test for delegation

### PR DESCRIPTION
**Pull request by ze97286**
close #3945 

more elaborate tests coming in soon.

### CODE REVIEW

**Review by peterbarrow — DISMISSED** [review]
Just minor spellings, otherwise looks really good.

**Review by peterbarrow — DISMISSED** [review]

**Review by ValentinTrinque — CHANGES_REQUESTED** [review]

**Review by ValentinTrinque — DISMISSED** [review]

**Review by cpuja84 — CHANGES_REQUESTED** [review]
My feedback on delegation tests

**Review by cpuja84 — COMMENTED** [review]
My comments

**Review by peterbarrow — DISMISSED** [review]

**Review by cpuja84 — APPROVED** [review]
Approved!

**Pull request merged**
