### PR TITLE
Seed orders in order to avoid broken references for a new Liquidity Provision

### LINKED ISSUE #6856: Liquidity provision order IDs pointing to non-existent orders
# Problem encountered
When running this query:

```
{
  marketsConnection {
    edges {
      node {
        id
        liquidityProvisionsConnection {
          edges {
            node {
              id
              sells {
                order{
                  id
                }
                liquidityOrder {
                  reference
                }
              }
              buys {
                order {
                  id
                }
                liquidityOrder {
                  reference
                }
              }
            }
          }
        }
      }
    }
  }
}
```
internal errors are returned, where orders should have been fetched.

# Observed behaviour
Liquidity provision order references IDs point to orders that have not yet been created, due to not being able to estimate best-bid and best-ask prices because at that point in the market lifetime we don't have any existing orders to get them from. This can be seen here: https://github.com/vegaprotocol/vega/blob/78c70dc8e3ccd533d68b4081ffecef77c1b96828/core/execution/liquidity_provision.go#L206

# Expected behaviour
Orders should exist for the generated IDs in the liquidity provision.

### PR DESCRIPTION
**Pull request by zale144**
Closes #6856

### CODE REVIEW

**Comment by zale144** [comment]
Tried testing it but got inconsistent results

**Comment by zale144** [comment]
Before fix (develop):
image

After fix (pr branch):
image

**Review by wwestgarth — DISMISSED** [review]

**Comment by MuthuVega** [comment]
```
"system-tests" : "fix_troubleshoot_liq_provision_orders"
```

**Comment by MuthuVega** [comment]
System Tests full run - https://jenkins.ops.vega.xyz/job/common/job/system-tests-nightly/518/

**Comment by jeremyletang** [comment]
@MuthuVega @zale144 there seems to be errors in the full run, could you guys take a look and confirm its due to this PR / it's not / fix it please?

**Comment by zale144** [comment]
> @MuthuVega @zale144 there seems to be errors in the full run, could you guys take a look and confirm its due to this PR / it's not / fix it please?

I think yes. The seeded orders are causing the test assertions to fail

**Review by wwestgarth — APPROVED** [review]

**Pull request merged**
