### PR TITLE
Add AC for 0008-TRAD-trading_workflow.md

### PR DESCRIPTION
**Pull request by Jiajia-Cui**
Add AC number in existing feature tests to address the ACs in 0008-TRAD-trading_workflow.md
Closes <https://github.com/vegaprotocol/vega/issues/4916>

### CODE REVIEW

**Review by davidsiska-vega — COMMENTED** [review]
I'd say let's stick with the convention that the codes go in the scenario name. It's really the whole scenario that's testing the AC not any single line.

**Review by cpuja84 — DISMISSED** [review]
Approved as the changes look good to me and can be merged once failing jobs are sorted

**Review by cpuja84 — DISMISSED** [review]
LGTM

**Review by cpuja84 — DISMISSED** [review]
The change LGTM and can be merged once CI jobs are passed

**Review by jeremyletang — DISMISSED** [review]

**Review by jeremyletang — APPROVED** [review]

**Pull request merged**
