### PR TITLE
Add price monitoring module

### PR DESCRIPTION
**Pull request by witgaw**
Adds price monitoring module. Not currently used, will get added to the market and connected to price monitoring triggers once #1963 and #1964 are done thus completing the price monitoring framework and allowing external testing.

### CODE REVIEW

**Review by witgaw — COMMENTED** [review]
Ready to be unWIPed.

**Review by qustavo — APPROVED** [review]
Idiomatic related comments only that might improve readability

**Review by edd — COMMENTED** [review]
**suggestion (non-blocking):** New folders means New Readmes. Please add documentation in the form of:

- monitor/README.md
- monitor/price/README.md
- monitor/liquidity/README.md

I'd mark this as blocking, but I don't mind if it's done in a separate PR straight after this one.

**Review by edd — COMMENTED** [review]
One comment request

**Pull request merged**
