### PR TITLE
Add GetTransaction to Block Explorer

### LINKED ISSUE #6435: add method to get a single transaction by hash to block explorer
Because the tendermint api to do this doesn't work when pg indexer is used

### PR DESCRIPTION
**Pull request by pscott31**
closes #6435

### CODE REVIEW

**Comment by jeremyletang** [comment]
This PR doesn't pass linters @pscott31, could you update it?

**Comment by pscott31** [comment]
fixed, apo-jollies

**Comment by jeremyletang** [comment]
> fixed, apo-jollies

Haha no worries! You mind pushing the code as well btw?

**Comment by pscott31** [comment]
managed to fail to commit the lint fixes the first time somehow.. trying again!

**Comment by jeremyletang** [comment]
> managed to fail to commit the lint fixes the first time somehow.. trying again!

Haha I supposed so. Thanks @pscott31

**Review by jeremyletang — APPROVED** [review]

**Pull request merged**
