### PR TITLE
fix: typo in node public key update

### LINKED ISSUE #6175: data node fails to process wallet key rotation - column "pub_key" of relation "nodes" does not exist
Running test

test_hot_key_rotation

Performs a wallet key rotation which sends a wallet tx - this then upsets the datanode 

```
2022-09-14T12:35:52.126+0100	ERROR	root	broker/sqlstore_broker.go:285	failed to process event id:"2608-8"  block:"7791E275131B66E512BDAD35903040E0B1661843A9C19C16BA38FB6B6359A00E"  type:BUS_EVENT_TYPE_KEY_ROTATION  key_rotation:{node_id:"ea872a80d8ef42cbbef7923fa70f2f86e1160849ec91492bf8b6ec4c6819f0b0"  old_pub_key:"ee2dcdc04bd1f0dd9a465b3a826fc046880e7d54ceebf1476d2202d8ebbddeb7"  new_pub_key:"c7c42fedd106d68e6261cc1759c7f7c7de413de8f37fd0bd7d38d7d4e0c7c73b"  block_height:2608}  version:1  chain_id:"test-chain-LnnTJl"  tx_hash:"7791E275131B66E512BDAD35903040E0B1661843A9C19C16BA38FB6B6359A00E" error:ERROR: column "pub_key" of relation "nodes" does not exist (SQLSTATE 42703)
Updating public key to SQL store failed
code.vegaprotocol.io/vega/datanode/sqlsubscribers.(*Node).consumeKeyRotation
	/Users/paulwebb/repos/vega/datanode/sqlsubscribers/node.go:121
code.vegaprotocol.io/vega/datanode/sqlsubscribers.(*Node).Push
	/Users/paulwebb/repos/vega/datanode/sqlsubscribers/node.go:76
code.vegaprotocol.io/vega/datanode/broker.(*sqlStoreBroker).push
	/Users/paulwebb/repos/vega/datanode/broker/sqlstore_broker.go:280
code.vegaprotocol.io/vega/datanode/broker.(*sqlStoreBroker).handleEvent
	/Users/paulwebb/repos/vega/datanode/broker/sqlstore_broker.go:268
code.vegaprotocol.io/vega/datanode/broker.(*sqlStoreBroker).processBlock
	/Users/paulwebb/repos/vega/datanode/broker/sqlstore_broker.go:227
code.vegaprotocol.io/vega/datanode/broker.(*sqlStoreBroker).Receive
	/Users/paulwebb/repos/vega/datanode/broker/sqlstore_broker.go:106
code.vegaprotocol.io/vega/cmd/data-node/commands/start.(*NodeCommand).runNode.func5
	/Users/paulwebb/repos/vega/cmd/data-node/commands/start/node.go:225
golang.org/x/sync/errgroup.(*Group).Go.func1
	/Users/paulwebb/Projects/go/pkg/mod/golang.org/x/sync@v0.0.0-20220722155255-886fb9371eb4/errgroup/errgroup.go:75
runtime.goexit
	/usr/local/Cellar/go/1.19.1/libexec/src/runtime/asm_amd64.s:1594
```

### PR DESCRIPTION
**Pull request by pscott31**
Closes #6175

### CODE REVIEW

**Comment by wwestgarth** [comment]
Minor: while you're here, could you remove this TODO? because it looks like its no longer relevant
https://github.com/vegaprotocol/vega/blob/develop/datanode/sqlstore/key_rotations.go#L54

**Comment by pscott31** [comment]
> Minor: while you're here, could you remove this TODO? because it looks like its no longer relevant https://github.com/vegaprotocol/vega/blob/develop/datanode/sqlstore/key_rotations.go#L54

Sure done & rebased

**Review by jeremyletang — APPROVED** [review]

**Comment by vega-paul** [comment]
> > Minor: while you're here, could you remove this TODO? because it looks like its no longer relevant https://github.com/vegaprotocol/vega/blob/develop/datanode/sqlstore/key_rotations.go#L54
> 
> Sure done & rebased

@wwestgarth doesnt this need to be done for eth key rotation test to see an uopdated datanode?

**Comment by vega-paul** [comment]
new full run https://jenkins.ops.vega.xyz/job/common/job/system-tests-nightly/95/

**Comment by wwestgarth** [comment]
> > > Minor: while you're here, could you remove this TODO? because it looks like its no longer relevant https://github.com/vegaprotocol/vega/blob/develop/datanode/sqlstore/key_rotations.go#L54
> > 
> > 
> > Sure done & rebased
> 
> @wwestgarth doesnt this need to be done for eth key rotation test to see an updated datanode?

Turns out the TODO made me think it was unimplemented but it turns out it is, even for the ethereum rotation the code exists: https://github.com/vegaprotocol/vega/blob/develop/datanode/sqlstore/node.go#L186

So I guess that issue is for whoever takes: https://github.com/vegaprotocol/vega/issues/6101

**Pull request merged**
